const express = require('express')
const app = express()
app.use(express.json())
app.get('/', (req, res) => res.send('hello world'))
app.post('/echo', (req, res) => res.json(req.body))
app.listen(process.env.PORT || 3000)
